default_stages: ["pre-commit", "commit-msg", "pre-push"]
default_language_version:
  python: python3
repos:
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: ['--unsafe']
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        name: lint with ruff
        types_or: [python, pyi, jupyter]
      - id: ruff
        name: sort imports with ruff
        types_or: [python, pyi, jupyter]
        args: [--select, I, --fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
